// Authored, user-facing copy shared across client surfaces. Use {appName} for
// product branding; appConfig.appName supplies it at runtime. HTML bindings
// escape the value before insertion.
import { appConfig } from './config.js';
// Keep product wording here when it appears in more than one place or is part
// of a flow that is rendered from both the SPA shell and JavaScript.
export const COPY = Object.freeze({
  about: Object.freeze({
    taglineHtml: '{appName} — your boutique fitness concierge.',
    disclaimerHtml: '{appName} gives you a one-stop-shop for finding and booking classes in your favuorute studios, all in one place:</br><ul><li>{appName} remembers your favourite spots and bikes, and books them for you automatically.<li><b>Auto-Book</b> secures your spot in class as soon as booking opens.<li><b>Auto-Upgrade</b> checks for a better spot 24/7, and upgrades you automatically.<li><b>Calendar Sync</b> keeps your Google and Apple Calendars up to date with classes as they are booked, changed or cancelled.<li><b>Flexible notifications</b> help you plan, and avoid cancellation penalties.</br><li>Supports Psycle, Barrys, SoulCycle, Aarmy, JAB Boxing Club and more!',
  }),
  onboarding: Object.freeze({
    welcomeTitle: 'Welcome to your boutique fitness concierge!',
    perkAutoBookTitle: 'Auto-Book',
    perkAutoBookText: 'Books your favourite spots the moment booking opens.',
    perkAutoUpgradeTitle: 'Auto-Upgrade',
    perkAutoUpgradeText: 'Checks for a better spot 24/7 and upgrades you.',
    perkCalendarTitle: 'Calendar Sync',
    perkCalendarText: 'Google and Apple Calendar stay up to date automatically.',
    perkNotifyTitle: 'Smart notifications',
    perkNotifyText: 'Plan ahead and avoid cancellation penalties.',
    supportedGyms: 'Supported gyms and studios',
    welcomeGyms: "Works with Psycle, Barry's, SoulCycle, Aarmy, JAB Boxing Club and more.",
    installEyebrow: 'Get the full experience',
    installTitle: 'Install {appName}',
    installButton: 'Install app',
    continueInBrowser: 'Continue in browser',
    installStepIosShare: 'Tap the <strong>Share</strong> button at the bottom of Safari.',
    installStepIosAdd: 'Scroll down and tap <strong>Add to Home Screen</strong>.',
    installStepIosConfirm: 'Tap <strong>Add</strong> in the top corner.',
    installStepIosOpen: 'Open {appName} from its new icon.',
    installIosOtherNote: 'Home Screen install only works from <strong>Safari</strong> on iPhone. Open this page in Safari (copy the address, or use your browser’s <strong>Open in Safari</strong> option), then follow these steps.',
    installStepAndroidMenu: 'Tap the <strong>⋮ menu</strong> in the top corner.',
    installStepAndroidInstall: 'Tap <strong>Install app</strong> (or <strong>Add to Home screen</strong>).',
    installStepAndroidConfirm: 'Tap <strong>Install</strong> to confirm.',
    installStepSamsungMenu: 'Tap the <strong>menu</strong> button (☰) at the bottom.',
    installStepSamsungAdd: 'Tap <strong>Add page to</strong>, then <strong>Home screen</strong>.',
    installStepGenericMenu: 'Open your browser’s menu.',
    installStepGenericAdd: 'Choose <strong>Add to Home screen</strong> or <strong>Install app</strong>.',
    back: '← Back',
    connectedGyms: 'Connected Studios & Gyms',
    connectAnotherGym: 'Connect Another Gym',
    connectNamedGym: 'Connect {gym}',
    connectGymAccount: 'Connect Your Gym Account',
    selectGym: 'Select Gym',
    gymLoginEmail: 'Gym Login Email/Username',
    gymPassword: 'Gym Password',
    backToSetup: 'Back to setup',
    allGymsConnected: 'All available gyms are connected!',
    allSetToBook: "You're all set to book across your connected gyms.",
    gymCredentialsRequired: 'Please enter your gym email and password.',
    notificationsTitle: 'Stay in the loop',
    notificationsDescription: 'Get instant alerts when your auto-bookings succeed, upgrades go through, or cancellation reminders fire.',
    calendarTitle: 'Stay organised',
    calendarDescription: 'Add classes to your calendar',
    calendarEnableDescription: 'Get your booked or tentative classes in {calendar} Calendar, kept in sync automatically — bookings, upgrades and cancellations all update on their own.',
    spotMapDescription: 'Set up your preferred spots in each studio so <b>Auto-Book</b>, <b>Quick-Book</b> and <b>Auto-Upgrade</b> can do the hard work for you. You can change your spots any time in Settings.',
    optionalSetup: 'Set up for the best experience',
    makeItYours: 'Make it yours',
    optionalSetupDescription: 'To help {appName} work for you, set up these key features. You can make changes or finish later in Settings.',
    autoUpgradeFeatureTitle: 'Auto-Upgrade',
    autoUpgradeFeatureDescription: 'Checks for a better spot 24/7 and upgrades you automatically.',
    autoUpgradeAllGyms: 'Turn on Auto-Upgrade for all my connected studios',
    autoUpgradeEnableFailed: 'Could not turn on Auto-Upgrade for {gyms}. You can enable it in Settings.',
    notificationUpdates: 'Get booking, upgrade and cancellation updates.',
    calendarFeedDescription: 'Keep your classes in a live calendar feed.',
    calendarSetupButton: 'Set up Calendar Sync',
    spotMapSetupButton: 'Set up Preferred Spot Maps',
    pushReasonTitle: 'Push notifications',
    enablePushTitle: 'Enable push notifications',
    tapToEnable: 'Tap to enable',
    pushUnavailable: 'Not available in this browser',
    spotMapEyebrow: 'Your favourite spots',
    pushReason: 'Booking, upgrade & cancellation alerts (required on iPhone & iPad).',
    offlineReasonTitle: 'Offline viewing',
    offlineReason: 'Your timetable & bookings stay available without signal.',
    installForExperience: 'Add {appName} to your device for the full experience.',
    installForHomeScreen: 'Add {appName} to your Home Screen for the full experience.',
    iosShareStepHtml: 'Tap the <strong>Share</strong> button {shareIcon} in Safari’s toolbar.',
    iosAddStep: 'Scroll down and tap <strong>Add to Home Screen</strong>.',
    iosOpenAppStep: 'Open {appName} from your new icon to continue.',
    yourGyms: 'Step 1: Your Studios',
    connectGymAccounts: 'Connect your gyms and studios',
    connectDescription: '{appName} connects directly to your gym accounts. Your logins are encrypted and stored in a secure private cloud, and you can delete them any time in Settings.',
    nameEyebrow: 'Make it yours',
    nameQuestion: 'Can I call you {name}?',
    namePrompt: 'What should we call you?',
    nameExplanation: 'We found this on your connected gym profile. You can change it any time.',
    nameInputLabel: 'First name',
    nameRequired: 'Please enter a first name.',
    yes: 'Yes',
    edit: 'Edit',
    saveAndContinue: 'Save and continue',
    connectAnotherLower: 'Connect another gym',
    continue: 'Continue',
    setupLater: 'Set up later',
    connecting: 'Connecting…',
    connectionFailed: 'Connection failed',
    notificationsEyebrow: 'Notifications',
    iosNotificationTitle: 'One more step on iPhone',
    iosNotificationHelp: 'To get push alerts on iOS, open {appName} from your Home Screen icon, then enable notifications from Settings.',
    enableNotifications: 'Enable notifications',
    maybeLater: 'Maybe later',
    calendarEnabled: 'Calendar enabled',
    subscribeCalendarTitle: 'Subscribe in your calendar app',
    addLiveFeed: 'Tap below to add the live feed to your calendar.',
    spotMapTitle: 'Set up your preferred spots and bikes',
    blockedBrowserSettings: 'Blocked — change this in browser settings',
    connectGymForSpotMaps: 'Connect a gym to use spot maps',
    recommended: 'Recommended',
    calendarSettings: 'Calendar settings & links',
    setUp: 'Set up',
    continueToTimetable: 'Continue to timetable',
    continueSetup: 'Get started',
    authChoiceTitle: 'Log in to {appName}',
    authChoiceLead: 'Log in, or create a {appName} account to get started.',
    logInButton: 'Log In',
    createAccountButton: 'Create Account',
    browserMenuStep: 'Open your browser’s <strong>⋮ menu</strong>.',
    browserInstallStep: 'Tap <strong>Install app</strong> or <strong>Add to Home screen</strong>.',
    googleCalendarButton: 'Add to Google Calendar',
    copyFeedUrl: 'Copy feed URL',
    done: 'Done',
    enableCalendar: 'Enable calendar',
    setUpNow: 'Set up now',
    calendarFeatureTitle: 'Calendar Sync',
    preferredSpotFeatureTitle: 'Preferred Spot Maps',
    preferredSpotFeatureDescription: 'The same preferred spots power <strong>Auto-Book</strong>, <strong>Quick-Book</strong> and <strong>Auto-Upgrade</strong>. Set them by gym, location and studio.',
    copied: 'Copied!',
    appleCalendarButton: 'Add to Apple Calendar',
    webcalButton: 'Subscribe via Webcal',
    connectGymButton: 'Connect Gym',
    setupLater: 'Set up later',
    slideLabel: 'Go to slide {number}',
    gymEmailPlaceholder: 'name@example.com',
    gymPasswordPlaceholder: '••••••••',
  }),
  auth: Object.freeze({
    logIn: 'Log In',
    logInSentenceCase: 'Log in',
    createAnAccount: 'Create an account',
    connectGym: 'Connect a gym',
    gymEmail: 'Gym email',
    gymPassword: 'Gym password',
    connectGymButton: 'Connect Gym',
    accountReady: 'Your account is ready. Add a gym login to start booking.',
    noGymsAvailable: 'No gyms available',
    couldNotLoadGyms: 'Could not load gyms',
    requiredGymCredentials: 'Gym, email and password are all required.',
    connecting: 'Connecting…',
    gymConnected: 'Gym connected',
    createAccount: 'Create Account',
    createAccountButton: 'Create Account',
    resetPassword: 'Reset password',
    resetUnavailable: 'Self-service reset isn’t available yet — contact the admin.',
    reauthenticationNeeded: 'Re-authentication needed',
    forgotPassword: 'Forgot password?',
    backToLogIn: 'Back to log in',
    passwordMinLength: 'Password must be at least 8 characters.',
    passwordMismatch: 'The two passwords don’t match.',
    creating: 'Creating…',
    accountCreated: 'Account created — now connect a gym',
    loginSuccess: 'Logged in successfully!',
    connectionFailed: 'Unable to connect. Check your internet connection.',
    offlineMutationBlocked: 'You’re offline. Reconnect before making changes.',
    incorrectCredentials: 'Incorrect email or password. Please try again.',
    sessionExpired: 'Session expired. Please log in again.',
    loggingIn: 'Logging in…',
    signInSubtitle: 'Sign in to your {appName} account.',
    createAccountSubtitle: 'Set up your {appName} account.',
    signupSubtitle: 'Set up your {appName} account. You’ll connect a gym next.',
    recoveryUnavailableLong: 'Self-service password reset isn’t available yet. Contact the admin to have your password reset.',
  }),
  api: Object.freeze({
    sessionExpired: 'Your session has expired. Please log in again.',
    cancelAction: 'Cancelling', joinWaitlistAction: 'Joining the waitlist', leaveWaitlistAction: 'Leaving the waitlist',
    commandFailed: '{action} failed', cancelPenaltyCheckFailed: 'Failed to check cancel penalty',
  }),
  bookingWindow: Object.freeze({
    weekOne: '{count} week', weekMany: '{count} weeks',
    through: '{window} · up to {date}', graceCancel: 'Cancel ({seconds}s)',
  }),
  pwa: Object.freeze({
    // Mirror these values in public/manifest.json and the SW fallback: both are
    // consumed before this Vite module exists, including while the app is offline.
    appName: '{appName}', shortName: '{appName}',
    manifestDescription: 'Progressive Web App for auto-booking and monitoring your gym classes.',
    pushTitleFallback: '{appName} Alert',
  }),
  tooltips: Object.freeze({
    instagram: 'Instagram', spotify: 'Spotify', stage: 'Stage',
    unmappedSpots: '+ {count} unmapped open spots',
  }),
  disciplines: Object.freeze({
    ride: 'Ride', barre: 'Barre', reformer: 'Reformer', pilates: 'Pilates', lagree: 'Lagree', recovery: 'Recovery', infrared: 'Infrared',
    yoga: 'Yoga', boxing: 'Boxing', train: 'Train', conditioning: 'Conditioning', strength: 'Strength',
    workshop: 'Workshop', bootcamp: 'Bootcamp', personalTraining: 'PT',
  }),
  common: Object.freeze({ gymNameJoiner: ' and ', classFallback: 'Class', ineligibleAtGym: 'Not eligible to book at this gym' }),
  notifications: Object.freeze({
    requiresInstall: 'Requires Install',
    iosInstallHelp: 'Add this app to your Home Screen to enable push notifications on iOS. Tap the Share button, then "Add to Home Screen".',
    unsupported: 'Unsupported',
    unsupportedHelp: 'Push notifications are not supported on this browser/device.',
    iosVersionHelp: 'Push notifications require iOS 16.4 or later. Please update your device.',
    permissionDenied: 'Push notification permission denied by user.',
    disablePush: 'Disable Push',
    pushEnabled: 'Push notifications are enabled on this device!',
    enablePush: 'Enable Push',
    pushHelp: 'Click to enable Web Push alerts on auto-bookings and upgrades.',
    pushDisabled: 'Push notifications disabled.',
    pushEnabledToast: 'Push notifications enabled successfully! 🔔',
    dismiss: 'Dismiss notification',
    customizePush: 'Choose which push notifications you receive. Changes apply to all your devices.',
    pushTestSent: 'Test notification sent to all devices.',
    gymConnectedToast: 'Gym connected successfully!',
  }),
  bookings: Object.freeze({
    loadingBookings: 'Loading bookings',
    loadingWaitlists: 'Loading waitlists',
    noBookings: 'No active bookings found.',
    openFloor: 'Open floor',
    cancelling: 'Cancelling booking...',
    bookingCancelled: 'Booking cancelled.',
    bookGuest: 'Book guest', guestMenu: 'Guest', guestBooked: 'Guest spot booked.', guestBookingUnavailable: 'Guest booking is not available for this class.',
    guestBookingError: 'Guest booking failed: {error}', guestEmail: 'Guest email address',
    selectGuestSpot: 'Choose an available spot for your guest on the live map.', guestNoSpot: 'This class has no available spots.',
    guestPassesRemaining: '{count} guest pass{plural} available for this class.', guestBookingSubmit: 'Book guest spot',
    guestSpotChip: 'Guest', selfSpotChip: 'You', guestMapSelf: 'Your spot', guestMapGuest: 'Guest spot',
    guestMapAvailable: 'Available', guestMapUnavailable: 'Unavailable', guestMapChoice: 'Guest choice',
    penaltyQuestion: 'Penalty?',
    cancel: 'Cancel', editSpotsTitle: 'Edit {noun}s: {className}',
    noChanges: 'No changes yet.',
    cancelBookingHelp: 'This releases all your spots and cancels the booking.',
    occupiedSpot: 'That spot is occupied.',
    noWaitlists: 'No active waitlists found.',
    waitlisted: 'Waitlisted',
    leaveWaitlist: 'Leave',
    leavingWaitlist: 'Leaving waitlist...',
    leftWaitlist: 'Left waitlist.',
    confirm: 'Confirm?',
    openFloorTitle: 'First come, first served — no assigned spot',
    startingUpgrade: 'Starting upgrade monitor...',
    upgradeStartedWithMap: 'Auto-upgrade monitor started using your saved spot map for this studio.',
    continuePastCutoff: 'Continue past 12h cutoff',
    disablingUpgrade: 'Disabling auto-upgrade...',
    upgradeDisabled: 'Auto-upgrade disabled.',
    preferredSpotRequired: 'Select at least one preferred spot for the upgrade to aim at.',
    upgradeUpdated: 'Auto-upgrade updated — shared spot map saved.',
    monitorStarted: 'Auto-upgrade monitor started! Monitoring for a better spot.',
    startMonitoring: 'Start Monitoring',
    saveChanges: 'Save Changes',
    currentSpotUnknown: 'Could not determine your current spot. Open the booking details to find your slot.',
    cancellationFailed: 'Cancellation failed: {error}', occupiedSpotFor: 'That {noun} is occupied.',
    editSpots: 'Edit spots', cancelBookingLabel: 'Cancel booking',
    autoUpgradeEnabledTitle: 'Configure/enable auto-upgrade', autoUpgradeDisabledTitle: 'Configure/disable auto-upgrade',
    waitlistJump: 'Waitlists ({count}) ↓',
    noCachedError: 'Error: {error}', loadingFloorMapError: 'Error loading layout: {error}',
    loadingSpotLayoutError: 'Error loading spot layout: {error}',
    noSpotsBookingHelp: '{reason} Use Cancel to release the booking.',
    editSpotsInstructionHtml: 'Tap to change your {noun}s. <strong style="color:var(--feat-autoupgrade);">Highlighted</strong> {noun}s are yours — deselect to release them, tap a free {noun} to add it. Saving releases removed {noun}s first, then books the added ones.',
    changes: 'Changes', selectedSpots: '{count} {noun}{plural} selected', spotsUpdated: '{noun}s updated.',
    spotSwapDeclined: 'Spot swap was declined', rebookedPartial: 'Re-booked {booked} of {total} spots — {declined}',
    remainingDeclined: 'the rest were declined', rebookingDeclined: 'Re-booking was declined',
    leaveWaitlistAria: 'Leave waitlist', preferredSpotRequiredFor: 'Select at least one preferred {noun} for the upgrade to aim at.',
    noCachedData: 'No cached data available', connectInternetBookings: 'Connect to the internet to load your bookings.',
    connectInternetWaitlists: 'Connect to the internet to load your waitlists.',
    updateFailed: "Couldn't update {noun}s: {error}",
    fetchingFloorMap: 'Fetching studio floor map...',
    loadingFloorMap: 'Loading studio floor map…', close: 'Close',
    disableUpgrade: 'Disable Auto-Upgrade',
  }),
  calendar: Object.freeze({
    onboardingIncludesGym: 'Includes your {gymName} classes.',
    onboardingIncludesGyms: 'Includes classes from {names} and {last} in one feed.',
    notPublished: 'Not published yet.',
    lastUpdated: 'Last updated {date}',
    connectGym: 'Connect a gym to start filling your calendar.',
    feedTitle: 'Calendar feed',
    feedOn: 'Feed is on',
    feedOff: 'Feed is off',
    feedOffDescription: 'Turn on to get a personal calendar link.',
    refreshNow: 'Refresh now',
    turnOffFeed: 'Turn off calendar feed',
    turnOnFeed: 'Turn on calendar feed',
    includeTitle: 'Include',
    includeDescription: 'Choose what appears in your calendar.',
    bookedClasses: 'Booked classes',
    alwaysIncluded: 'Always included.',
    waitlists: 'Waitlists',
    tentativeWaitlists: 'Classes you are waitlisted for, shown as tentative.',
    autoBook: 'Auto-Book',
    tentativeAutoBook: 'Scheduled Auto-Book classes, shown as tentative.',
    weeklyReminder: 'Remind me when weekly booking opens',
    weeklyReminderHelp: 'Adds an event when booking opens at {gyms}, with a 15-minute alert.',
    reminders: 'Reminders',
    reminderDescription: 'Event reminders from your calendar app. Applied to booked classes only.',
    twoHoursBefore: '2 hours before class',
    leaveReminder: 'A reminder shortly before you need to leave.',
    beforeCancellationEnds: 'Before free cancellation ends',
    cancellationReminder: '12 hours before class, when free cancellation closes.',
    addToCalendar: 'Add to calendar',
    feedUpdatesDescription: 'Your feed updates itself: bookings, upgrades and cancellations follow automatically.',
    appleCalendar: 'Apple Calendar',
    googleCalendar: 'Google Calendar',
    copyLink: 'Copy link',
    updated: 'Calendar feed updated.',
    linkCopied: 'Calendar link copied.',
    copyFailed: 'Could not copy the link — long-press it to copy manually.',
    turnedOff: 'Calendar feed turned off.',
    turnedOn: 'Calendar feed turned on.',
    refreshing: 'Calendar feed refreshing.',
    loadingFailed: "Couldn't load calendar settings ({error})",
    noSavedStatus: "You're offline and this device has no saved calendar status yet.",
  }),
  credits: Object.freeze({
    soonestExpiry: 'Soonest expiry {date}',
    renews: 'Renews {date}', expires: 'Expires {date}',
    member: 'Member', inactive: 'Inactive', membership: 'Membership', notActive: 'Not active',
    buyCredits: 'Buy credits →', manageAtGym: 'Manage at gym ↗',
    noCreditPacks: 'No credit packs here',
    membershipTopUpDescription: 'This gym runs on memberships rather than credits, so there is nothing to top up. Classes are booked against your membership directly.',
    experimental: 'EXPERIMENTAL',
    experimentalPurchaseNotice: 'Purchasing bundles works but is not well-tested. This app sends the order directly to {gymName} using your saved cards, so it never sees your payment data. It doesn’t support 3-D Secure, so payments might fail.',
    allStudios: 'All Studios', selectStudios: 'Select Studios',
    allWorkouts: 'All Workouts', excludesLagree: 'Excl. Lagree', firstOnly: '1st Only', returningCustomer: '✔ Rtn Customer', oneTime: '1-Time', repeatPurchase: '✔ Rpt Purchase',
    avoidsThreeDSecure: 'Tips to avoid 3-D Secure',
    cardTrustedTip: 'Use a card your bank already trusts for {gymName}.',
    websitePurchaseTip: 'Complete one purchase on the {gymName} website first — banks usually stop challenging after that.',
    amexTip: 'Amex cards are challenged less often than Visa/Mastercard.',
    finishOnWebsite: 'Finish on Website', paymentNotCompleted: 'Payment not completed',
    connectGym: 'Connect a gym to see your booking allowance.', checkingAllowance: 'Checking your allowance…',
    topUpRequired: 'You cannot book here until you top up.', noMembership: 'No membership found',
    membershipRequired: 'Bookings will be refused until this gym has an active membership.',
    creditBundles: 'Credit bundles', experimental: 'EXPERIMENTAL', loadingBundles: 'Loading bundles...',
    noCreditsHere: 'No credit packs here',
    creditAvailableOne: 'credit available', creditAvailableMany: 'credits available',
    creditsKind: 'Credits', membershipKind: 'Membership',
    activeMembershipMissing: 'No active membership found', managedByGym: 'Memberships are managed by {gym}.',
    openWebsite: 'Open website ↗', unpinBundle: 'Unpin', creditsCount: '{count} Credits',
    closeModal: 'Close', remove: 'Remove', creditsAdded: '{count} credits added to your account.',
    declined: 'The payment was declined.', paymentOptionsFailed: "Couldn't load payment options: {error}",
    noSavedCard: 'No saved card found on your {gym} account.', addCardHint: 'Add a card on the {gym} website, then try again.',
    creditBreakdown: '{count} credit{plural} · {price} each', buyFor: 'Buy {price}', creditUnit: '/ credit', payTotal: 'Pay {total}',
    bundleId: '(ID: {id})', notAvailable: 'N/A',
    noCachedBundles: 'No cached data available', loadBundlesHelp: 'Connect to the internet to load credit bundles.',
    membershipNotCredits: 'This gym runs on memberships rather than credits, so there is nothing to top up. Classes are booked against your membership directly.',
    noBundleMatches: 'No bundles match the current filters.', favouriteBundles: 'Favourite Bundles',
    allCredits: 'All Credits', cart: 'Cart', totalIncVat: 'Total (inc. VAT)',
    continueToPayment: 'Continue to Payment →', payment: 'Payment', processingPayment: 'Processing payment…',
    paymentComplete: 'Payment complete', creditsPurchased: 'Credits purchased!',
    unsupportedSecureCard: "This card needs 3-D Secure authentication, which isn't supported in-app yet.",
    finishOnWebsite: 'Finish on Website', bundlePinned: 'Bundle pinned to favourites.', bundleUnpinned: 'Bundle unpinned.',
    categories: 'Categories', hideCategories: 'Hide Categories', tipsThreeDSecure: 'Tips to avoid 3-D Secure',
    loadingSavedCards: 'Loading saved cards…', payWith: 'Pay with', done: 'Done', pinBundle: 'Pin to favorites',
  }),
  autoBook: Object.freeze({
    planningSlots: '📋 Planning: attempting slots [{slots}]',
    attemptingSlot: '🎯 Attempting slot {slot} ({kind})...',
    bookedSlotsStatus: '✅ Success! Booked slots [{slots}]', firing: 'Firing…', bookingNow: 'Booking now',
    nextLabel: 'Next: {label}',
    joinedWaitlistStatus: '✅ Joined waitlist',
    bookedStatus: 'Booked', waitlistedStatus: 'Waitlisted', failedStatus: 'Failed',
    previousPage: 'Prev', nextPage: 'Next',
    nothingQueued: 'Nothing queued', releaseUnknown: 'Release time unknown',
    resume: 'Resume Auto-Book',
    pause: 'Pause Auto-Book',
    paused: 'Auto-book paused',
    resumed: 'Auto-book resumed',
    simulateRelease: 'Simulate Release',
    failed: 'Failed: {error}',
    editTitle: 'Edit Auto-Book: {className}', class: 'Class',
    editingMapHtml: 'You are editing your preferred spot map for <strong>{studioName}</strong>. Changes here apply to Quick-Book and Auto-Upgrade too.',
    failedStudioLayout: 'Failed to load studio layout: {error}',
    pausedHeadline: 'Auto-Book paused',
    edit: 'Edit',
    loadingQueueLabel: 'Loading auto-book queue', loadingHistoryLabel: 'Loading auto-book history',
    simulatedRelease: 'Simulated release fired — all pending bookings executing now. Check history shortly.',
    noCachedData: 'No cached data available',
    noCachedDataHelp: 'Connect to the internet to load your auto-book queue.',
    noScheduledClasses: 'No classes scheduled in the release queue. Visit the Timetable tab to add classes.',
    insufficientCredits: 'Insufficient Credits',
    confirm: 'Confirm?',
    removing: 'Removing scheduled booking...',
    removed: 'Class removed from queue.',
    loadingFloorMap: 'Fetching studio floor map...',
    unassignedSpots: "This class doesn't use assigned spots.",
    noFloorMap: 'No floor map layout available for this studio.',
    noFloorMapHelp: 'You can still update the number of spots and fallback option below.',
    slotsToBook: 'Slots to book:',
    fallbackAnySlot: 'Book any slot if preferred is unavailable',
    saveChanges: 'Save Changes',
    preferredMapHelp: 'Auto-Book uses your preferred spot map to book the best spot it can. You can edit your preferred spots any time in Settings.',
    savingChanges: 'Saving auto-book changes...',
    updated: 'Auto-book configuration updated!',
    noHistory: 'No execution history yet.',
    standingBy: 'Standing by to book',
    noClassesWaiting: 'No classes waiting to book',
    openNow: 'Open now',
    bookingWindowOpen: 'Booking window open',
    bookingPaused: 'Auto-book paused',
  }),
  autoUpgrade: Object.freeze({
    loading: 'Loading auto-upgrade monitors',
    loadFailed: 'Error: {error}',
    actionFailed: 'Error: {error}',
    insufficientCredits: '⚠ Insufficient Credits',
    noMonitors: 'No active auto-upgrade monitors running. You can set them up from the <strong>My Bookings</strong> tab.',
    monitoring: 'Monitoring Active',
    pausedDisabled: 'Paused: polling off for this gym',
    upgraded: 'Upgraded (12h window)',
    stopped: 'Stopped',
    configure: 'Configure',
    stop: 'Stop',
    stopping: 'Stopping upgrade monitor...',
    stoppedToast: 'Upgrade monitor stopped.',
    configureTitle: 'Configure Auto-Upgrade',
    editTitle: 'Edit Auto-Upgrade',
    configureClassTitle: 'Auto-Upgrade: {className}',
    backToUpgrade: 'Back to Auto-Upgrade',
    start: 'Start Monitoring',
    disable: 'Disable Auto-Upgrade',
  }),
  gyms: Object.freeze({
    connected: 'Connected',
    noGymsLinked: 'No gyms linked. Add one to start booking.',
    noAvailableGyms: 'Every available gym is already connected.',
    loadingSettings: 'Loading gym settings…',
    connectGym: 'Connect a gym',
    linkBeforeSettings: 'Link a gym before configuring booking settings.',
    gymUnlinked: 'Gym unlinked.',
    gymLinked: 'Gym linked',
    reauthenticated: 'Re-authenticated',
    reconnect: 'Reconnect needed',
    notAvailable: 'Not available yet',
    membershipUnavailable: 'Membership details are managed by the gym and are not available yet.',
    notRecorded: 'Not recorded',
    lastAuthToday: 'Today · {date}',
    lastAuthYesterday: 'Yesterday · {date}',
    lastAuthDaysAgo: '{days} days ago · {date}',
  }),
  gymSettings: Object.freeze({
    pollingOneMinute: '1 minute', pollingFifteenMinutes: '15 minutes', pollingOneHour: '1 hour',
    settings: 'Gym settings',
    addAnotherGym: '＋ Connect another gym',
    reconnect: 'Reconnect this gym',
    reconnectHelp: 'The saved gym session could not be renewed. Re-authenticate to resume background bookings and calendar updates.',
    connection: 'Connection',
    reauthenticate: 'Re-authenticate',
    unlink: 'Unlink gym',
    membershipCredits: 'Membership & Credits',
    bookingWindow: 'Booking Window',
    manualOverride: 'Manual override',
    debugOverrideHelp: 'Debug only; overrides auto-detection.',
    autoDetected: 'Auto (detected)',
    autoUpgradeEngine: 'Auto-Upgrade Engine',
    spotMapHelp: 'Manage the seat preferences used by booking and Auto-Upgrade at this gym.',
    manageMaps: 'Manage maps',
    profileExplorer: 'Profile Explorer',
    profileExplorerHelp: 'View the profile, membership and booking metadata returned by this gym.',
    openProfileExplorer: 'Open Profile Explorer',
    publishedBookingWindow: 'Published per class by the gym — there is nothing to configure.',
    detectingMembership: 'Detecting from your membership…',
    enablePolling: 'Enable Auto-Upgrade Polling',
    pollingHelp: 'Toggle background checks for improved spots at this gym.',
    pollingOffNote: 'Polling is off: existing monitors at this gym are paused (not deleted) and the options below are disabled until you turn it back on.',
    autoUpgradeByDefault: 'Auto-upgrade spots by default',
    autoUpgradeByDefaultHelp: 'Start monitoring after each new booking at this gym.',
    continueCutoffByDefault: 'Continue past 12h cutoff by default',
    continueCutoffHelp: 'Keep monitoring without cancelling the original spot.',
    pollingInterval: 'Polling check interval',
    pollingIntervalHelp: 'One-minute checks are faster but use more API calls.',
    membershipManagedByGym: 'Membership details are managed by the gym and are not available yet.',
    activeCreditBundles: 'Across your active credit bundles.',
    openGymSite: 'Open gym site',
    genericGym: 'Gym',
    gymAccountEmailNotCaptured: 'Gym account email not captured',
    membershipName: 'Gym membership',
    membershipActive: 'Active',
    guestPassesOne: '{count} guest pass left',
    guestPassesMany: '{count} guest passes left',
    weekOptionOne: '{count} week',
    weekOptionMany: '{count} weeks',
  }),
  settings: Object.freeze({
    noGymsLinked: 'No gyms linked. Add one to start booking.', reauthenticateGym: 'Re-authenticate {gym}',
    noAvailableGyms: 'Every available gym is already connected.',
    loadingGymSettings: 'Loading gym settings…',
    connectGym: 'Connect a gym', linkBeforeConfig: 'Link a gym before configuring booking settings.',
    linkGym: 'Link gym', link: 'Link gym', addGym: 'Add a gym', reauthenticate: 'Re-authenticate', unlink: 'Unlink',
    confirmUnlink: 'Confirm unlink?', unlinkGym: 'Unlink gym', gym: 'Gym', email: 'Email', password: 'Password',
    changeAccountPassword: 'Change account password', currentPassword: 'Current password',
    newPassword: 'New password', confirmNewPassword: 'Confirm new password', changePassword: 'Change password',
    deleteData: 'Delete All My Data', confirmDelete: 'Are you sure? Click again to confirm.', deleting: 'Deleting...',
    allDataDeleted: 'All data deleted. Logging out.',
    confirmRemove: 'Confirm remove?', discardUnsaved: 'You have unsaved changes. Exit edit mode and discard them?',
    editEnabled: 'Edit mode enabled', editDisabled: 'Edit mode disabled', noChanges: 'No changes to save',
    profileSaved: 'Profile saved and verified', profileVerificationFailed: 'Saved but verification failed: {error}',
    profileSaveFailed: 'Save failed: {error}', lastAuthenticated: 'Last authenticated',
    reauthenticated: 'Re-authenticated', gymLinked: 'Gym linked', gymUnlinked: 'Gym unlinked.',
    accountPasswordChanged: 'Account password changed', settingsSaved: 'Settings saved successfully.',
    loggingOut: 'Logging out...', configExporting: 'Preparing config export...',
    configExported: 'Config exported successfully!', importingConfig: 'Importing configuration...',
    configImported: 'Config imported successfully! Reloading data...', defaultsRemoved: 'Studio defaults removed!',
    spotMapSaved: 'Saved spot map for {studio}', done: 'Done', changePasswordButton: 'Change password',
    checking: 'Checking…', changePasswordSaving: 'Saving…',
    notificationSpotBooked: 'Spot Booked', notificationSpotBookedHelp: 'When a class is successfully booked.',
    notificationSpotUpgraded: 'Spot Upgraded', notificationSpotUpgradedHelp: 'When auto-upgrade moves you to a better spot.',
    notificationCreditWarning: 'Credit Warning', notificationCreditWarningHelp: "When you set something up but don't have enough credits.",
    notificationCancellationReminder: 'Cancellation Reminder', notificationCancellationHelp: 'Reminder to cancel before the free-cancel window closes.',
    notificationBookingWindow: 'Booking Window Reminder', bookingWindowRollingNote: 'Not available: this gym has a rolling booking window, not a weekly release.', notificationBookingWindowHelp: 'Heads-up before your booking window opens.',
    gymConnections: 'Gym connections', connection: 'Connection', actions: 'Actions', reconnectNeeded: 'Reconnect needed',
    connectGymAction: '＋ Connect a gym', couldNotLoadGyms: "Couldn't load your gyms ({error})",
    gymSettingsSaved: '{gym} settings saved.', gymSettingsSaveFailed: "Couldn't save {gym} settings: {error}",
    unlinkFailed: "Couldn't unlink gym: {error}", loadGymSettingsFailed: "Couldn't load gym settings ({error})",
    noSavedGymData: "You're offline and this device has no saved gym connections yet.",
    noSavedGymSettings: "You're offline and this device has no saved settings for this gym yet.",
    profileLoadFailed: 'Unable to load profile data. Connect to the internet to sync. ({error})',
    studiosLoadFailed: 'Unable to load studios. Connect to the internet to sync. ({error})',
    floorPlanLoadFailed: 'Unable to load floor plan. Connect to the internet to sync. ({error})',
    spotMapSaveFailed: 'Save failed: {error}',
    actionFailed: 'Failed: {error}', notificationSaveFailed: 'Failed to save notification settings: {error}',
    pushTestFailed: 'Test failed: {error}', settingsSaveFailed: 'Error saving settings: {error}',
    exportFailed: 'Export failed: {error}', importFailed: 'Import failed: Invalid JSON or format. {error}', deleteFailed: 'Delete failed: {error}',
    addGymCredentialsHelp: 'Enter your current credentials for this gym. Use this if you changed your password there and bookings started failing.',
    linkGymCredentialsHelp: 'Sign in with that gym’s own credentials. They’re encrypted before being stored, and only ever used to talk to that gym.',
    accountPasswordDescription: 'This is your {appName} password — separate from any gym’s. Changing it here doesn’t change your password at the gym, and vice versa.',
    newPasswordMinPlaceholder: 'At least 8 characters', passwordMinimumError: 'New password must be at least 8 characters.',
    passwordMismatchError: 'The two new passwords don’t match.',
    allBookings: 'All Bookings', autoBookOnly: 'Auto-Book only', cancellationDayBefore: '1 day before (24h)', beforePenalty: 'Before penalty (14h)',
  }),
  profileExplorer: Object.freeze({
    title: 'Profile Explorer', gymTitle: '{gymName} Profile Explorer', loading: 'Loading profile…', dataUnavailable: 'No profile data loaded.',
    noActiveCredits: 'No active credits.', unknown: 'Unknown', creditHandle: 'Handle: {handle}', creditsLeft: '{count} Left',
    noPlans: 'No subscription plans found.', planHandle: 'Plan: {handle}', editBanner: '🔓 Edit Mode Enabled — modify fields and click Save Changes', exitEdit: 'Enter konami code again to exit',
    changeLog: '📝 Change Log', saveChanges: '💾 Save Changes', readOnly: '(read-only)', noChanges: 'No changes yet.',
    sectionBasicInfo: 'Basic Info', sectionAccountPayments: 'Account & Payments', sectionMetafieldsPreferences: 'Metafields & Preferences',
    sectionBookingStats: 'Booking Stats & Cutoffs', sectionAvailableCredits: 'Available Credits', sectionSubscriptions: 'Subscriptions & Plans', sectionOther: 'Other',
  }),
  spotMaps: Object.freeze({
    preferredSpotMaps: 'Preferred Spot Maps', loadingStudios: 'Loading studios…',
    noTimetableData: 'No Timetable Data', noSeatMaps: 'No Studios With Seat Maps', removing: 'Removing…',
    loadTimetableFirst: 'Please open the Timetable tab first to load classes, then return here.',
    noSeatLayouts: 'No studios with seat layouts were found in the current timetable.',
    editSpots: 'Edit Spots', chooseSpots: 'Choose Spots', remove: 'Remove',
    confirmRemove: 'Confirm remove?', defaultsRemoved: 'Studio defaults removed!', spotMap: 'Spot Map',
    loadingFloorPlan: 'Loading floor plan…', noFloorMapAvailable: 'No floor map available',
    anySpotHelp: 'Preferences will apply to any available spot when booking at this studio.',
    saveAnySpot: 'Save (Any Spot Preference)', noSelection: '(None selected yet)',
    dragToPan: 'Drag to pan the map', clearPreferences: 'Clear Preferences',
    preferredSpotsCount: '{count} preferred spot{plural}', preferredRowsCount: '{count} preferred row{plural}',
    sharedSpotMapHtml: 'This is the one shared preferred spot map for <strong>{studioName}</strong>. Quick-Book, Auto-Book, and Auto-Upgrade at this studio all use it — changes apply everywhere.',
  }),
  timetable: Object.freeze({
    loadingTimetable: 'Loading timetable',
    configureAutoBook: 'Configure Auto-Book',
    configureQuickBook: 'Configure Quick-Book',
    quickBook: 'Quick-Book',
    checkingAvailability: 'Checking availability…',
    loadingFloorMap: 'Fetching studio floor map…',
    noFloorMap: 'No floor map layout available for this studio.',
    scheduleAnySeat: 'Schedule Auto-Book (Any Seat)',
    scheduleAutoBook: 'Schedule Auto-Book',
    studioOccupancy: 'Studio Occupancy',
    metadataFailed: 'Failed to load filters metadata.',
    allFiltersCleared: 'All filters cleared.',
    overlayFiltered: 'Filtered: {labels}',
    overlayNoFilters: 'no filters',
    overlayFavourites: 'Favourites',
    overlayClear: 'Clear',
    overlayUnavailable: '{count} unavailable',
    overlayGymIgnored: 'You are not linked to {gyms}, so that part of the link was ignored.',
    overlaySaveBlocked: 'These filters came from a link. Clear them before saving defaults.',
    filtersSaved: 'Current filters saved as defaults on this device!',
    filtersSaveFailed: 'Failed to save filters.',
    noTimetableCache: 'No cached timetable available',
    internetForTimetable: 'Connect to the internet to load the timetable.',
    retry: 'Retry', allGyms: 'All Gyms', gym: 'Gym',
    allLocations: 'All Locations', location: 'Location',
    allInstructors: 'All Instructors', instructor: 'Instructor',
    allTypes: 'All Types', type: 'Type',
    searchInstructors: 'Search instructors…',
    removeBookmark: 'Remove Bookmark', bookmarkClass: 'Bookmark Class',
    autoBook: 'Auto-Book', scheduled: 'Scheduled', edit: 'Edit', booked: 'Booked',
    manage: 'Manage', leaveWaitlist: 'Leave WL', onWaitlist: 'On Waitlist',
    joinWaitlist: 'Join Waitlist', full: 'Full', buyCredits: 'Buy Credits',
    noMembership: 'No Membership', book: 'Book', quickBookTitle: 'Quick book',
    failedBookmarkId: 'Error generating bookmark ID.', bookmarkRemoved: 'Removed bookmark.',
    bookmarkAdded: 'Class bookmarked successfully!', bookmarkUpdateFailed: 'Failed to update class bookmark.',
    classDataFailed: 'Could not load class data.', fullyBookedJoining: 'Fully booked! Joining waitlist...',
    waitlistJoined: 'Joined waitlist successfully!', bookingDeclined: 'Booking was declined',
    noEligibleSlots: 'No eligible slots available matching preferences.',
    autoUpgradeMapRequired: "Can't set auto-upgrade because you don't have a preferred spot map for {studio}. Please configure one!",
    monitorStartedCount: 'Auto-upgrade monitor started for {count} spot(s).',
    spotBooked: 'Spot booked successfully!{note} 🎉', bookingFailed: 'Booking failed: {error}',
    cancelFailed: 'Cancel failed: {error}', autoBookScheduled: 'Successfully scheduled auto-book for {className}!',
    autoBookScheduleFailed: 'Failed to schedule auto-book: {error}',
    quickBookError: 'Quick Book error: {error}', waitlistFailed: 'Waitlist failed: {error}',
    leftWaitlistError: 'Error leaving waitlist: {error}',
    bookingWaitlistTip: '💡 Tip: Enable "Auto-upgrade spots by default" in Settings to monitor for better slots automatically!',
    autoUpgradeTip: '💡 Tip: Enable "Auto-upgrade spots by default" in Settings to monitor for better slots automatically!',
    quickBookConfirmSoon: 'Starts soon — confirm?', confirm: 'Confirm?',
    cancelBooking: 'Cancelling booking...', occupiedNow: '⚠ Currently occupied — will be targeted when booking fires.',

    chooseSpotBook: 'Book (choose a spot)', unfavourite: 'Unfavourite', favourite: 'Favourite',
    clearFilters: 'Clear Filters', saveDefaults: 'Save Defaults',
    removingScheduled: 'Removing scheduled booking...',
    scheduledCancelled: 'Scheduled auto-book cancelled.',
    bookingNotFound: 'Booking not found — refresh and try again.',
    joinedWaitlist: 'Successfully joined waitlist!',
    leftWaitlist: 'Left waitlist successfully!',
    noBookmarkSupport: 'This gym does not support bookmarks.',
    quickBooked: 'Quick-booked! 🎉',
    quickBookFailed: 'Failed to quick book any slots.',
    confirmCancel: 'Confirm cancel?',
    confirmSoon: 'Class starts soon. Confirm?',
    joining: 'Joining...', leaving: 'Leaving...', booking: 'Booking...',
    cancel: 'Cancel', cancelling: 'Cancelling...',
    cancelled: 'Booking cancelled successfully!',
    scheduling: 'Scheduling auto-booking...',
    noDates: 'No dates match filter criteria.',
    prevWeek: 'Previous week', nextWeek: 'Next week',
    noClasses: 'No classes match the current filters. Clear filters to see more.',
    timeColumn: 'Time', gymColumn: 'Gym', classColumn: 'Class', instructorColumn: 'Instructor',
    locationStudioColumn: 'Location / Studio', statusColumn: 'Status', actionsColumn: 'Actions',
    notLive: 'Not Live', waitlisted: 'Waitlisted', waitlist: 'Waitlist', noCredits: 'No credits',
    confirmLeave: 'Confirm leave?', configureAutoBookAria: 'Configure auto-book', configureQuickBookAria: 'Configure quick-book',
    moreActions: 'More actions', filterOptions: 'Filter options', favourited: 'Favourited',
    instructorProfileAria: 'View instructor profile for {name}', scheduledShort: 'Sched.',
    upgradeEnabledNote: ' Auto-upgrade enabled.', quickBookedDetail: 'Quick-booked{slots}!{upgrade} 🎉',
    errorPrefix: 'Error: {error}', selectSpotInStudio: 'Select a {noun} in the studio',
    bookAnyAvailable: 'Book Any Available {noun}', seatTitle: 'Seat {label}',
    occupiedUnavailable: '⚠ This {noun} is occupied or unavailable.',
    removeRow: 'Remove Row {row}', addRow: 'Add Row {row}', additionalAvailableSpots: '⚠ Additional Available Spots:',
    autoBookCreditShortfall: 'In order for Auto-Book to work, you need to purchase {count} more credit{plural}.',
    quickBookCreditShortfall: 'In order for Quick-Book to work, you need to purchase {count} more credit{plural}.',
    editingSharedMapHtml: 'You are editing your preferred spot map for <strong>{studio}</strong>. Changes here apply to Quick-Book and Auto-Upgrade too.',
    sharedMapForStudioHtml: 'Spots here are your one shared preferred map for <strong>{studio}</strong>. Scheduling updates it for Quick-Book and Auto-Upgrade too.',
    slotsToBook: 'Slots to book:', bookAnyPreferred: 'Book any slot if preferred is unavailable',
    autoUpgradeNeedsSpots: 'Auto-Upgrade: Please configure your preferred spots for {studio} first.',
    autoUpgradeKeepSearching: 'Auto-Upgrade: Keep searching for a better spot for me',
    bookingWindowIsOpen: '✓ Booking window is open', bookingOpens: 'Booking opens: {date}',
    ineligibleCreditsAvailable: '{count} credit{plural} available.',
    bookSelectedCount: 'Book Selected {noun}',
    bookPrompt: 'Select the {noun}s you want to book for this class. You have {count} credit{plural} available.',
    pleaseSelectSpots: 'Please select at least one {noun} to book.',
    insufficientCreditsForSelection: 'You only have {credits} credit{creditPlural} available, but selected {count} {noun}{nounPlural}.',
    quickBookMapHelp: 'Quick-Book uses your preferred spot map to book the best spot it can. You can edit your preferred spots any time in Settings.',
    quickBookFirstSetupHtml: 'First time setup: Quick-Book grabs a preferred spot in any class in one click. Set your preferred spots for <strong>{studio}</strong> once and they\'ll apply everywhere.',
    quickBookBannerHtml: 'Quick-Book uses your preferred spot map to book the best spot it can. You can edit your preferred spots any time in Settings.',
    editingQuickBookMapHtml: 'You are editing your preferred spot map for <strong>{studio}</strong>. Changes here apply to Auto-Book and Auto-Upgrade too.',
    pleaseSelectSpotOrRow: 'Please select at least one {noun} or row to book.',
    errorLoadingLayout: 'Error loading layout: {error}',
    quickBookFailedMessage: 'Quick book failed: {error}',
    auto: 'Auto',
    moreCount: '+{count} more',
    simpleBookCreditShortfall: 'In order to book, you need to purchase {count} more credit{plural}.',
    autoUpgradeConfigureFirstHtml: 'Auto-Upgrade: Please <a href="#" id="simplebook-configure-link" style="color:var(--feat-autoupgrade);text-decoration:underline;cursor:pointer;">configure your preferred spots</a> for <strong>{studio}</strong> first.',
    mapEditInstructionHtml: 'Tap studio spots in the order you prefer them. Choose as many as you like!',
    mapEditRowsInstruction: 'You can also choose entire rows with the + button, but individual spots will be most preferred when booking.',
    autoUpgradeConfigurePrompt: 'Auto-Upgrade: Please configure your preferred spots for this studio first.',
    autoUpgradeKeepSearchingLabel: 'Auto-Upgrade: Keep searching for a better spot for me',
    bookAnyPreferredFallback: 'Book any slot if preferred is unavailable',
    preferredLabel: 'Preferred',
    rowLabel: 'Rows',
    spotLabel: 'Spots',
    confirmPenaltyCancel: 'Cancel this booking? A cancellation penalty may apply.',
    bookSelectedPlain: 'Book Selected {noun}s',
    simpleBookPrompt: 'Select the {noun}(s) you want to book for this class. You have {count} credit{plural} available.',
    simpleBookSelectedCredits: 'You only have {credits} credit{creditPlural} available, but selected {count} {noun}{nounPlural}.',
    remainingDeclined: 'the rest were declined',
    noCachedTimetable: 'No cached timetable available',
    noCachedData: 'No cached data available', connectInternetBookings: 'Connect to the internet to load your bookings.',
    connectInternetWaitlists: 'Connect to the internet to load your waitlists.',
    connectInternet: 'Connect to the internet to load the timetable.',
    autoBookModalTitle: 'Auto-Book: {time} {className}{instructor}',
    quickBookModalTitle: 'Configure Quick-Book for {studio}: {time} {className}{instructor}',
    chooseSeatFor: 'Choose a {noun} for {time} {className}{instructor}',
    maxSpots: 'You can select up to {count} {noun}{plural}.',
    editPreferredSpots: 'Edit preferred spots for {studio}',
    bookSelected: 'Book Selected {noun}s',
    bookCountPartial: 'Booked {booked} of {total} — {declined}',
    bookedCount: 'Successfully booked {count} {noun}{plural}!{note} 🎉',
    bookingSpot: 'Booking spot {slot}...',
    loadingLayout: 'Loading layout...',
    failedOccupancy: 'Failed to load occupancy data.',
    stage: 'STAGE', savingFilters: 'Saving...', savedFilters: '✓ Saved!',
    selectedOne: '{count} Selected', selectedMany: '{count} {label}{plural}',
    opensInPrefixHtml: '<span class="ab-cd-prefix">Opens in </span>',
    opensInDaysOne: '{prefix}{count} day', opensInDaysMany: '{prefix}{count} days',
    opensInHoursOne: '{prefix}{count} hour', opensInHoursMany: '{prefix}{count} hours',
    opensInMinutesOne: '{prefix}{count} min', opensInMinutesMany: '{prefix}{count} mins',
  }),
  shell: Object.freeze({
    offline: "You're offline! Some features are unavailable.",
    offlineSavedData: "You're offline. Showing saved data from {time}; changes are disabled.",
    noMembership: 'No membership',
    noMembershipBadge: '0',
    membershipActive: 'Membership active',
    creditUnit: 'credits', creditBadgeTitle: '{gymName}: {total} credit{plural} available',
    membershipBadgeTitle: '{gymName}: Membership active', member: 'Member',
    noActiveMembership: 'No active membership', ineligibleBadgeTitle: '{gymName}: {reason}',
    openGymSettings: 'Open {gymName} settings',
    gymSessionExpired: '{gymName}: session expired. Reconnect it in Settings → Your Gyms.',
  }),
  accessibility: Object.freeze({
    loadingCards: 'Loading',
    configureAutoUpgrade: 'Configure auto-upgrade',
    stopAutoUpgrade: 'Stop auto-upgrade',
    showCardActions: 'Show actions (edit or cancel)',
    hideCardActions: 'Hide actions',
    editCard: 'Edit',
  }),
  filters: Object.freeze({
    clearLabel: 'Clear {label}',
    clearFilterChip: 'gym and location filters',
    locationsCompact: '{count} Location{plural}',
    gymQuickGroup: 'Show classes from',
    gymQuickShown: '{name}, shown',
    gymQuickHidden: '{name}, hidden',
    gymQuickUnlinked: '{name}, not connected',
    gymQuickConnectHint: 'Connect {name} in Settings > Your Gyms to see its classes.',
    workoutFilterChip: 'workout filters',
    instructorFilterChip: 'instructor filters',
    instructorFallback: 'Instructor',
    noLocationsForGyms: 'No locations for the selected gyms.',
    filters: 'Filters',
    bookmarkedOnly: 'Bookmarked classes only',
    types: 'Types',
    instructors: 'Instructors',
    all: 'All',
    selected: '{count} selected',
    clear: 'Clear',
    noInstructorsMatch: 'No instructors match.',
    noInstructorsForGyms: 'No instructors for the selected gyms.',
    searchInstructors: 'Search instructors',
    locations: 'Locations',
    workouts: 'Workouts',
    resetAll: 'Reset all',
    closeFilters: 'Close filters',
    saveAsDefault: 'Save as default',
    noClassesAdjust: 'No classes – adjust filters',
    showClasses: 'Show classes',
    activeFilters: '{count} active',
    searchInstructorsAria: 'Search instructors',
    search: 'Search classes',
    class: 'class',
    classes: 'classes',
  }),
  search: Object.freeze({
    placeholder: 'Search classes, instructors, gyms…',
    label: 'Search the timetable',
    open: 'Search',
    clearInput: 'Clear search text',
    searchFor: 'Search all classes for “{text}”',
    loading: 'Loading classes…',
    resultsFor: 'Search: {text}',
    filteredResults: 'Search results',
    saveBlocked: 'Leave search to save default filters.',
    clear: 'Clear',
    results: '{count} upcoming classes',
    resultsOne: '1 upcoming class',
    none: 'No upcoming classes match “{text}”.',
    groupInstructor: 'Instructors', groupClass: 'Classes', groupLocation: 'Locations', groupGym: 'Gyms', groupWorkout: 'Workouts',
    count: '{count} upcoming',
    suggestionsAria: 'Search suggestions',
  }),
  overlap: Object.freeze({
    newAutobook: 'New auto-book', autoBookAnyway: 'Auto-book anyway',
    autoBookTail: 'Auto-book will try to book both, and you can cancel one later.',
    alreadyBookedAutoBook: 'You already have a booking in this class. Auto-book will have nothing to add.',
    newBooking: 'New booking', bookAnyway: 'Book anyway', quickBookAnyway: 'Quick-Book anyway',
    bothCanBookTail: 'You can book both and cancel one later.', alreadyBooked: 'You already have a booking in this class.',
    alreadyBookedTitle: 'Already booked', overlappingTitle: 'Overlapping class',
    bookedClass: 'a class you have booked', queuedClass: 'another class in your auto-book queue',
    anotherClass: 'another class', overlapsPrefix: 'This overlaps ',
    clashesWith: 'Clashes with', cancel: 'Cancel',
    inQueue: 'In your queue', booked: 'Booked', new: 'New',
    more: 'and {count} more', class: 'Class',
  }),
  pullToRefresh: Object.freeze({
    refreshing: 'Refreshing...', release: 'Release to refresh', pull: 'Pull to refresh',
  }),
  spotSelection: Object.freeze({
    firstTimeSetup: 'First-time setup', chooseSpots: 'Choose your preferred spots for {where} first.',
    setupBodyHtml: 'Once set up, <b>Quick-Book</b> and <b>Auto-Book</b> will always book the best possible spot for you.',
    next: 'Next', thisStudio: 'this studio',
  }),
  spotMapEditor: Object.freeze({
    preferred: 'Preferred', currentSeat: 'Spot {label} (Your current seat)',
    preferredPriority: 'Spot {label} — preference #{priority}',
    currentPreferredPriority: 'Spot {label} — preference #{priority} (your current seat)',
    occupiedPreferredSeat: 'Spot {label} (Occupied but preferred)',
    dragToPan: 'Drag to pan the map',
    moreCount: '+{count} more',
    podium: 'Podium',
    noneSelected: '(None selected yet)',
    editInstructionHtml: 'Tap studio spots in the order you prefer them. Choose as many as you like!',
    editRowsInstruction: 'You can also choose entire rows with the + button, but individual spots will be most preferred when booking.',
    clearPreferences: 'Clear Preferences',
    saveMapAnd: 'Save map and',
    spots: 'Spots',
    rows: 'Rows',
    saveDefaults: 'Save Defaults',
    disable: 'Disable',
    editPreferredSpots: 'Edit preferred spots',
  }),
  spotSetup: Object.freeze({
    title: 'Set your preferred spots',
    eyebrow: 'Set up once per studio',
    headline: 'Tell us where you like to work out',
    point1: 'Pick your favourite spots at {studio}, in order of preference.',
    point2: 'We use them every time you Quick-Book, Auto-Book or Auto-Upgrade.',
    point3: 'Change them whenever you like in Settings.',
    reassure: 'Nothing is booked yet. This takes about 20 seconds.',
    choose: 'Choose my spots', chooseForNow: 'Choose a spot for now',
    save: 'Save my spots', saving: 'Saving…', retry: 'Retry',
    none: 'No spots chosen yet', one: '1 spot chosen', many: '{count} spots chosen',
    needOne: 'Pick at least one spot to save your preferences.',
    offline: "You're offline. Reconnect to save your spots.",
    saveFailed: "Couldn't save your spots. Check your connection and try again.",
    loadFailed: "We couldn't load the floor plan.",
    discardConfirm: "Discard your spots?\n\nYou haven't saved your changes.",
    savedTitle: 'Your spots are saved',
    savedBody: 'Next time, Quick-Book and Auto-Book will go for these spots at {studio} first.',
    continueTo: 'Continue to book {className}', editSpots: 'Edit spots',
    stepYourSpots: 'Your spots', stepBook: 'Book class',
    stepLabelA: 'Step 1 of 2: Your spots', stepLabelB: 'Step 2 of 2: Book class',
    needsSpots: 'Auto-Upgrade needs your preferred spots', setUpSpots: 'Set up spots',
  }),
  bookingFlow: Object.freeze({
    titleBook: 'Book your spot', titleFinishQuickBook: 'Finish Quick-Book', titleAutoBook: 'Schedule Auto-Book', titleEditAutoBook: 'Edit Auto-Book',
    titleUpgrade: 'Auto-Upgrade', titleEditSpots: 'Change your spots',
    thisClass: 'This class', withInstructor: 'with {instructor}', spotLeft: '{count} spot left', spotsLeft: '{count} spots left',
    dismissTip: 'Dismiss tip',
    helperAutoBookAt: 'Spots are picked the moment booking opens at {time}. Your numbered spots go first.',
    opensIn: 'Opens in {countdown}', bookingOpen: 'Booking is open',
    fcfsAutoBook: 'This class has no assigned spots, so we will book you in as soon as it opens.',
    spotsToBook: 'Spots to book',
    simpleSetupBanner: 'Save your preferred spots to Quick-Book next time.',
    offline: "You're offline. Reconnect to book.",
    reconnectGym: 'Reconnect {gym} to book.', reconnectAction: 'Reconnect',
    helperLive: 'Your preferred spots are numbered. Tap any free spot to choose a different one just for this class.',
    autoChosenSpotSentence: '{appName} chose spot {slot} based on your spot map.',
    helperAutoBook: 'Spots are picked the moment booking opens. Your numbered spots go first.',
    helperSetup: 'Tap studio spots in the order you prefer them. Choose as many as you like!',
    helperSetupRows: 'You can also choose entire rows with the + button, but individual spots will be most preferred when booking.',
    oneOffSpots: 'Choose spots for this class only. They will not change your saved studio preferences.',
  }),
  bookingEditor: Object.freeze({
    discardChanges: 'Discard changes?',
    noAssignedSpots: 'This class doesn’t use assigned {noun}s, so there’s nothing to change here.',
    noAssignedUpgradeSpots: 'This class doesn’t use assigned {noun}s, so there’s nothing to upgrade to.',
    noFloorMap: 'No floor map is available for this studio, so {noun}s can’t be changed here.',
    noMapForUpgrade: 'No floor map is available for this studio. Auto-Upgrade requires a spot map.',
    cancelBookingReleaseSpots: 'This releases all your {noun}s and cancels the booking.',
    selfBookingLimit: 'You can choose up to {count} personal spot{plural} for this class. Guest spots do not count toward this limit.',
    bookingLimitUnavailable: 'Booking limits could not be confirmed. Refresh the class and try again.',
    selfBookingLimitExceeded: 'You can book up to {count} personal spot{plural} for this class.',
    upgradeNeedsCredits: 'In order for Auto-Upgrade to work, you need to purchase {needed} more credit(s) from {gym}.',
    sharedSpotMapHtml: 'This is the one shared preferred spot map for <strong>{studioName}</strong>. Changes also affect Auto-Book and Quick-Book.',
    finalUpgradeAttempt: 'Within 12h of class, make one final upgrade attempt without cancelling your original {noun}.',
    finalUpgradeAttemptHelp: 'Within 12h of class, make one final upgrade attempt without cancelling your original {noun} — you’ll need to ask the gym to release it. Without this, monitoring stops at 12h.',
    creditShortfall: 'You need {shortfall} more credit{creditPlural} to add {count} {noun}{nounPlural}.',
  }),
  occupancy: Object.freeze({
    class: 'Class Occupancy',
    studio: 'Studio Occupancy',
    available: 'Available',
    booked: 'Booked',
    loadingLayout: 'Loading layout...',
    failedLayout: 'Failed to load slot layout.',
    total: 'Total',
    open: 'Open',
  }),
  home: Object.freeze({
    title: 'Home', subtitle: 'Your classes and bookings at a glance.',
    comingSoon: 'Coming soon', loadingWidget: 'Loading', error: "Couldn't load this.", retry: 'Retry',
    connectGymTitle: 'Connect a gym', connectGymBody: 'Connect a gym to see your classes, bookings and credits here.', connectGymAction: '＋ Connect a gym',
    noGymWidget: 'Connect a gym to see this.', gymsLoadFailed: "Couldn't check your gyms.",
    welcome: 'Welcome', book: 'Book a class', bookAll: 'All', upcoming: 'Upcoming classes', autoBook: 'Auto-Book', credits: 'Credits',
    favourites: 'Favourites', topInstructors: 'Top instructors', stats: 'Your stats', noCredits: 'No credits or active memberships yet.',
    autoBookActive: 'active auto-book entries', autoBookNone: 'No active auto-book entries yet. Tap to set one up.', autoBookOne: 'active auto-book entry',
    upcomingNone: 'No upcoming classes. Book one from the timetable.', viewAll: 'View all bookings', upcomingStripLabel: 'Next 7 days', upcomingToday: 'Today',
    refresh: 'Refresh Home',
  }),
  navigation: Object.freeze({
    home: 'Home', timetable: 'Class Timetable', bookings: 'My Bookings', autoBook: 'Auto-Book',
    credits: 'Credits & Membership', settings: 'Settings',
  }),
  static: Object.freeze({
    navPrimary: 'Primary', navHome: 'Home', navTimetable: 'Timetable', navBookings: 'Bookings', navAutoBook: 'Auto-Book',
    navCredits: 'Credits and membership', navCreditsVisual: 'Credits', navSettings: 'Settings', headerLoading: 'Loading...',
    errorOpeningTab: 'Error opening tab: {error}', emailPlaceholder: 'name@example.com',
    linkedGymFallback: 'A linked gym',
    exampleEmail: 'name@example.com', passwordPlaceholder: '••••••••', passwordMinimumPlaceholder: 'At least 8 characters',
    studioFallback: 'Studio', locationFallback: 'Location', yourGymFallback: 'your gym', unknownLocation: 'Unknown Location',
    refresh: 'Refresh', refreshTimetable: 'Refresh timetable', refreshBookings: 'Refresh bookings',
    refreshAutobookQueue: 'Refresh auto-book queue', refreshCreditBundles: 'Refresh credit bundles',
    theme: 'Theme', refreshing: 'Refreshing...',
    selectStudioSeat: 'Select Studio Seat', profileExplorer: 'Profile Explorer',
    addGym: 'Add a gym', debugClassDiagnostics: 'Debug: Class Diagnostics',
    loadingDebugData: 'Loading debug data...', notificationPreferences: 'Notification Preferences',
    debugLog: 'Debug Log',
    emailAddress: 'Email Address',
    confirmPassword: 'Confirm password',
    passwordAtLeastEight: 'At least 8 characters',
    email: 'Your {appName} email',
    emailContinue: 'Continue',
    accountPrivacy: 'Your {appName} account is separate from your gym logins. Gym login credentials are encrypted and stored in a secure private cloud. Stored data can be deleted at any time from Settings.',
    aboutSecurity: 'Your login details are encrypted with your account, and stored securely in a  private cloud. You can delete your {appName} account and stored data at any time from Settings.',
    aboutAutoBook: 'Automatically book at the exact millisecond a class is opened for your account, helping you secure the best spots.',
    aboutAutoUpgrade: 'Monitors your booked class 24/7, and upgrades you to a better spot if one becomes available.',
    aboutQuickBook: 'Books your preferred spot in any class in one click, using your saved seat preferences per studio.',
    aboutSpotMaps: 'Save your favourite seat positions per studio. Set this up for each studio to power Quick-Book, Auto-Book, and Auto-Upgrade.',
    aboutPush: 'Receive instant alerts on your device when you\'re Auto-Booked or Auto-Upgraded.',
    aboutCalendar: 'Add your classes to Apple or Google Calendar. Bookings, upgrade, and cancellations update on their own.',
    privacyData: 'Privacy & Data',
    privacyDescription: '{appName} uses your gym login credentials to do its magic, and they are saved within your account. Your data is encrypted and stored in a secure private cloud. You can delete your account, all your data and gym logins at any time from Settings.',
    welcomeTourDescription: 'Replay the introduction and setup walkthrough for {appName}.',
    generalDescription: 'Appearance, behaviour and backup — settings that apply to your whole {appName} account.',
    timetableSubtitle: 'Book classes directly or schedule them for release.',
    allGyms: 'All Gyms', gyms: 'GYMS', locations: 'LOCATIONS', allLocations: 'All Locations',
    instructors: 'INSTRUCTORS', allInstructors: 'All Instructors', workoutTypes: 'WORKOUT TYPES',
    allTypes: 'All Types', bookmarked: '♡ Bookmarked', clear: 'Clear', save: 'Save',
    fetchingClasses: 'Fetching timetable classes...',
    bookingsTitle: 'My Bookings & Waitlists',
    bookingsSubtitle: 'Manage your active slots, waiting list status, and seat upgrade preferences.',
    activeBookings: 'Active Bookings', activeWaitlists: 'Active Waitlists', nextBookingIn: 'Next booking in',
    readyToBook: 'Ready to book', autoBookQueue: 'Auto-Book Queue', history: 'History',
    creditSubtitle: 'Your booking allowance and purchase options for each connected gym.',
    allGymsBack: '← All gyms', searchBundles: 'Search bundles (e.g. 5 pack, Clapham, Ride)...',
    categories: 'Categories', singleCredits: 'Single credits & top-ups',
    singleCreditsHelp: 'Single-class credits and top-up / add-on packs',
    studioLocationBundlesHelp: 'Bundles tied to a specific studio/location (Victoria, Clapham, Shoreditch, Bank…) and at-home/online',
    memberStudentBundlesHelp: 'Student, member, corporate, graduate and unlimited/membership bundles',
    introBundlesHelp: 'Intro/welcome offers, partner, event, promotional, free/test and expired bundles',
    studioLocationBundles: 'Studio & location-specific', memberStudentBundles: 'Member, student & corporate',
    introBundles: 'Intro, promo & other',
    about: 'About', general: 'General', calendarSync: 'Calendar Sync', notifications: 'Notifications',
    yourGyms: 'Your Gyms', account: 'Account', back: 'Back', aboutHeading: 'Why?',
    features: 'Features', preferredSpotMaps: 'Preferred Spot Maps', pushNotifications: 'Push Notifications',
    welcomeTour: 'Welcome Tour', replayOnboarding: 'Replay Onboarding', appearance: 'Appearance',
    chooseTheme: 'Choose light or dark, or follow your device automatically.',
    auto: 'Auto', light: 'Light', dark: 'Dark', appBehaviour: 'App Behaviour',
    performancePreferences: 'Performance preferences shared across every linked gym.',
    prefetchRange: 'Timetable Prefetch Range',
    prefetchHelp: 'Number of weeks to prefetch when loading the timetable (1–8).',
    prefetchWeek1: '1 week', prefetchWeek2: '2 weeks', prefetchWeek3: '3 weeks', prefetchWeek4: '4 weeks',
    prefetchWeek5: '5 weeks', prefetchWeek6: '6 weeks', prefetchWeek7: '7 weeks', prefetchWeek8: '8 weeks',
    backupMigration: 'Backup & Migration',
    configMigrationHelp: 'Import or export configuration JSON compatible with the Chrome extension.',
    exportConfig: 'Export Config JSON', importConfig: 'Import Config JSON',
    debugMode: 'Debug Mode',
    debugModeHelp: 'Show raw API diagnostics, class JSON and troubleshooting controls.',
    enableDebugMode: 'Enable Debug Mode', debugModeDetail: 'Exposes debug actions throughout the app.',
    calendarDescription: "One calendar feed covering every gym you've connected. Stays in sync with bookings, waitlists and cancellations.",
    notificationsDescription: 'Push notifications on this device, and which kinds you want.',
    webPush: 'Web Push Notifications',
    registerPushHelp: 'Register this device to receive alerts on auto-bookings and upgrades.',
    pushSubscriptionStatus: 'Push Subscription Status',
    pushSubscriptionHelp: 'Click button to enable notifications on this device.',
    enablePush: 'Enable Push', customizeNotifications: 'Customise Notifications',
    testNotifications: '🔔 Test Notifications',
    testNotificationsHelp: 'Send a sample of each notification to all your signed-in devices.',
    spotBooked: 'Spot Booked', spotUpgraded: 'Spot Upgraded',
    spotUpgradedKeptOriginal: 'Spot Upgraded (kept original, <12h)',
    creditWarningAutobook: 'Credit Warning (Auto-Book)',
    creditWarningUpgrade: 'Credit Warning (Auto-Upgrade)',
    cancellationReminder: 'Cancellation Reminder',
    bookingWindowAutoBook: 'Booking Window (has Auto-Book)',
    bookingWindowNoAutobook: 'Booking Window (no Auto-Book)',
    bookingWindowInsufficientCredits: 'Booking Window (insufficient credits)',
    accountPassword: 'Account Password', accountSession: 'Account Session',
    changeAccountPassword: 'Change account password',
    accountDescription: 'Your {appName} login and your data.',
    passwordDescription: 'Your {appName} password is separate from every gym password.',
    accountSessionDescription: 'Clear local session tokens and log out of {appName}.',
    logout: 'Log Out',
    deleteData: 'Delete All My Data',
    deleteDataHelp: 'Permanently delete this account, encrypted credentials, queues, preferences and push subscriptions. This cannot be undone.',
    gymsDescription: "Connect gyms and manage each gym's own booking settings.",
    gymsHelp: "Re-authenticate a gym, unlink one, or connect another. Every linked gym's classes already appear together in the timetable and your bookings.",
    loading: 'Loading…',
    loggingIn: 'Logging in…', saving: 'Saving…', savingDots: 'Saving...',
    changePassword: 'Change password',
    gym: 'Gym',
    sessionExpired: 'Your gym session expired. Reconnect it in Settings → Your Gyms.',
    noDatesMatch: 'No dates match filter criteria.',
    noClassesMatch: 'No classes match the current filters. Clear filters to see more.',
    refreshing: 'Refreshing...',
  }),
});

function lookupCopy(key) {
  return String(key || '').split('.').reduce((value, part) => value?.[part], COPY);
}

/** Fill trusted, authored HTML slots in the SPA shell before onboarding clones them. */
export function formatCopyText(template, values = {}) {
  return String(template).replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key) => (key in values ? String(values[key]) : match));
}

/** Format authored copy with the runtime app name (HTML-escaped). The one path for {appName}. */
export function appCopy(template, values = {}) {
  return formatCopyText(template, { appName: escapeHtml(appConfig.appName), ...values });
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
}

export function applyStaticCopy(root = document, { appName = appConfig.appName } = {}) {
  root.querySelectorAll('[data-copy-text]').forEach((element) => {
    const text = lookupCopy(element.dataset.copyText);
    if (typeof text === 'string') element.textContent = formatCopyText(text, { appName });
  });
  root.querySelectorAll('[data-copy-html]').forEach((element) => {
    const html = lookupCopy(element.dataset.copyHtml);
    if (typeof html === 'string') element.innerHTML = formatCopyText(html, { appName: escapeHtml(appName) });
  });
  root.querySelectorAll('[data-copy-placeholder]').forEach((element) => {
    const value = lookupCopy(element.dataset.copyPlaceholder);
    if (typeof value === 'string') element.setAttribute('placeholder', value);
  });
  root.querySelectorAll('[data-copy-aria-label]').forEach((element) => {
    const value = lookupCopy(element.dataset.copyAriaLabel);
    if (typeof value === 'string') element.setAttribute('aria-label', value);
  });
  root.querySelectorAll('[data-copy-title]').forEach((element) => {
    const value = lookupCopy(element.dataset.copyTitle);
    if (typeof value === 'string') element.setAttribute('title', value);
  });
}
