version: '3.8'

services:
  psycle-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psycle-app-dev
    ports:
      - "100.86.226.52:3005:3000"
    volumes:
      - ./data:/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
      - edge

networks:
  edge:
    external: true
    name: edge

volumes:
  psycle-data:
